### PR TITLE
Updates for Ataraxia

### PR DESCRIPTION
**Pull request by protonesso**

### CODE REVIEW

**Comment by FabioLolix** [comment]
Great, I have a few comments (also this is in its early days and haven't made guidelines yet and there is room for improvement)

about packages is for the type/format like deb, rpm, pkg.tar.xz, etc. guess I should change to packaging. the number of packages is overkill IMHO

In the table I **want** the 'real' things; I have browsed the latest release and haven't seen a Sway iso or i686, aarch64, armv7hnl, armv6hl, ppc64le, ppc64, ppc, riscv64 iso/image
If is possible to build Ataraxia for a lot of architectures or install additional dekstops is very welcome for the description

The other things are ok

There is a page about boostrap/build? I'm sure I have seen it in the past

This is the only complete page https://github.com/FabioLolix/Lolix-lists/blob/master/os/linux/b/bbqlinux.md 

Also for the description are welcome mentions of name chages (if possible with date), drop or addition of CPU architectures or very important features

**Comment by protonesso** [comment]
>haven't seen build for other architectures
https://github.com/ataraxialinux/ataraxia/releases/tag/tp2

**Comment by FabioLolix** [comment]
> > haven't seen build for other architectures
> 
> https://github.com/ataraxialinux/ataraxia/releases/tag/tp2

very well


Another question, can I browse the Ataraxia repository with a browser (I guess yes, if so where?)

**Comment by protonesso** [comment]
There's repository but slightly outdated I will build packages when tech preview 3 will be released (very soon): https://protonesso.moe/Ataraxia

Also packages.iso

**Comment by protonesso** [comment]
updated some

**Comment by FabioLolix** [comment]
Well, I will merge it

**Pull request merged**
